### PR TITLE
add getUnspentAll JSON RPC method

### PR DESCRIPTION
**Pull request by troggy**
Required for https://github.com/leapdao/leap-node/pull/174 to be useable

### CODE REVIEW

**Comment by troggy** [comment]
FYI @StevenJNPearce 

stumbled across the inability to call `web3.getUnspent()` without parameters. Hence this PR

**Comment by sunify** [comment]
It should be possible. Checking web3 internals

**Comment by troggy** [comment]
@sunify 
https://github.com/ethereum/web3.js/blob/v1.0.0-beta.36/packages/web3-core-method/src/index.js#L123

**Comment by johannbarbie** [comment]
it works:
screen shot 2019-02-22 at 10 37 54 am

but has errors in typescript:
```

ERROR in /Users/johba/dev/bridge-ui/src/routes/status.tsx
./src/routes/status.tsx
[tsl] ERROR in /Users/johba/dev/bridge-ui/src/routes/status.tsx(180,46)
      TS2339: Property 'getUnspentAll' does not exist on type 'ExtendedWeb3'.

ERROR in /Users/johba/dev/bridge-ui/src/stores/unspents.ts
./src/stores/unspents.ts
[tsl] ERROR in /Users/johba/dev/bridge-ui/src/stores/unspents.ts(253,46)
      TS2345: Argument of type 'JSBI' is not assignable to parameter of type 'number | JSBI'.
  Type 'import("/Users/johba/dev/bridge-ui/node_modules/jsbi/jsbi").default' is not assignable to type 'import("/Users/johba/dev/leap-core/node_modules/jsbi/jsbi").default'.
    Types have separate declarations of a private property 'length'.
```

**Comment by StevenJNPearce** [comment]
I've added the typedef; should get rid of the error.

**Pull request merged**
