### PR TITLE
improve bundling, parcel:dist/browser.js

### LINKED ISSUE #82: Support for proper bundling for in the `dist` step
# Bounty
Use `gulp` or something similar to bundle the distribution js files,
to make it outright usable to `<script src...>` it :)

## Scope
- bundling

## Deliverables
Super convenient way to add leap-core support to a webpage

## Gain for the project
🌮 

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

### PR DESCRIPTION
**Pull request by pinkiebell**
- use parcel-bundler and introduce `dist/leap-core.min.js` to have an easy way to include it in webapps. (window.LeapCore)
- fix import/export from class objects (parcel does not like it)
- fix babel to not transform *.spec.js files

Fixes #82

### CODE REVIEW

**Comment by sunify** [comment]
I'm not happy with browserify. I've tried to use Parcel for bundling, it's works perfect and result bundle weights 300Kb less than with browserify.

Besides that, it's awesome. I can switch it to Parcel (or webpack) for you.

P.S. i didn't find any bounty for that, so i'll pay for that PR from dev curator budget

**Comment by pinkiebell** [comment]
@sunify 
Thanks for the awesome hint 😃 
Upgraded to parcel-bundler, I only had one problem with `util.js` where parcel-bundler doesn't like `import { foo, bar } from './util'` if `util = export class  {}`

**Comment by pinkiebell** [comment]
> I don't think we should bundle `index.js`. Much better would be keep it as it was — just transpiled files

Any reason why we should transpile at all if we want the same files in dist? 
We could just remove ES6/import-export and node modules could use `lib/index` out of the box

**Comment by sunify** [comment]
Yeah, but we support browsers as well, and it's common practice to ship es5 code

**Comment by pinkiebell** [comment]
> Yeah, but we support browsers as well, and it's common practice to ship es5 code

Other projects using the webpack/browserify/whatelse pipeline transpiling it again.
The only reason I wanted a standalone `browser.js` is for people who don't use that or just want to quick-hack a webpage which uses the plasma chain. And that is the point of `browser.js`.
They still had to bundle it with the dependencies with what we had before.
And on the node.js side, there is really no good reason  for transpiling stuff except for a faster startup time and old node.js support (really old)

**Comment by sunify** [comment]
Yeah, they are using webpack, babel and so on, but often babel is disabled for `node_modules`, that's why would be better to transpile code.

Anyway, let's change only one thing here — add bundle for browsers (minified)

**Comment by pinkiebell** [comment]
> Yeah, they are using webpack, babel and so on, but often babel is disabled for `node_modules`, that's why would be better to transpile code.
> 

Which it is in `dist/index.js` without bundled dependencies for the `node` target.
I'm just confused why you are thinking that individual files would be any better if the goal is transpiling.
Because it would also mean that we would have 2 different tools just for transpiling stuff instead of 1.

> Anyway, let's change only one thing here — add bundle for browsers (minified)

**Comment by sunify** [comment]
I don't want to throw parcel's shit into webpack/browserify/rollup bundles of users. These bundlers can handle things in own way and our bundled index.js can break it

**Comment by pinkiebell** [comment]
Changed. I wasn't aware that webpack has a problem with that 🤷‍♂️

**Comment by sunify** [comment]
> I wasn't aware that webpack has a problem with that 🤷‍♂️

The point is do not mess with a way how people bundle their apps

**Pull request merged**
